# Core and Platform Settings
option('enable_ppe', type : 'integer', min : -1, max : 1, value : -1)
option('tracker_use_simd', type : 'integer', min : -1, max : 1, value : -1)
option('pci_platform', type : 'string', value : 'V70')
option('vvas_core_utils', type : 'string', value : 'GLIB')

# Feature Components
option('scaler', type : 'feature', value : 'disabled')
option('decoder', type : 'feature', value : 'disabled')
option('overlay', type : 'feature', value : 'disabled')
option('metaaffixer', type : 'feature', value : 'disabled')
option('utils', type : 'feature', value : 'enabled')     # Kept for vvas_xfilter support
option('tracker', type : 'feature', value : 'disabled')
option('dpuinfer', type : 'feature', value : 'disabled')
option('metaconvert', type : 'feature', value : 'disabled')

# AI Models (All disabled by setting value to '0')
option('CLASSIFICATION', type: 'string', value: '0')
option('VEHICLECLASSIFICATION', type: 'string', value: '0')
option('YOLOV2', type: 'string', value: '0')
option('YOLOV3', type: 'string', value: '0')
option('REFINEDET', type: 'string', value: '0')
option('PLATEDETECT', type: 'string', value: '0')
option('PLATENUM', type: 'string', value: '0')
option('FACEDETECT', type: 'string', value: '0')
option('EFFICIENTDETD2', type: 'string', value: '0')
option('BCC', type: 'string', value: '0')
option('SSD', type: 'string', value: '0')
option('TFSSD', type: 'string', value: '0')
option('ULTRAFAST', type: 'string', value: '0')
option('ROADLINE', type: 'string', value: '0')
option('FACELANDMARK', type: 'string', value: '0')
option('FACEFEATURE', type: 'string', value: '0')
option('POSEDETECT', type: 'string', value: '0')
option('REID', type: 'string', value: '0')
option('SEGMENTATION', type: 'string', value: '0')
option('RAWTENSOR', type: 'string', value: '0')