# Feature options for plugins without external deps
option('enable_xrm', type : 'integer', min : -1, max : 1, value : -1)
option('enable_ppe', type : 'integer', min : -1, max : 1, value : -1)
option('tracker_use_simd', type : 'boolean', value : false)
option('pci_platform', type : 'string', value : 'V70')
option('vvas_core_utils', type : 'string', value : 'GLIB')

# KEEPING OPTIONS KNOWN BUT DISABLED
option('metaaffixer', type : 'feature', value : 'disabled')
option('roigen', type : 'feature', value : 'disabled')
option('filter', type : 'feature', value : 'enabled')  # ENABLED
option('multisrc', type : 'feature', value : 'enabled') # ENABLED
option('videodec', type : 'feature', value : 'disabled')
option('abrscaler', type : 'feature', value : 'disabled')
option('metaconvert', type : 'feature', value : 'disabled')
option('infer', type : 'feature', value : 'disabled')
option('funnel', type : 'feature', value : 'disabled')
option('defunnel', type : 'feature', value : 'disabled')
option('overlay', type : 'feature', value : 'disabled')
option('optflow', type : 'feature', value : 'disabled')
option('multicrop', type : 'feature', value : 'disabled')
option('compositor', type : 'feature', value : 'disabled')
option('tracker', type : 'feature', value : 'disabled')
option('skipframe', type : 'feature', value : 'disabled')
option('reorderframe', type : 'feature', value : 'disabled')

# Common feature options
option('examples', type : 'feature', value : 'disabled', yield : true)